### ISSUE TITLE
Code for Primitive fitting.

### ISSUE THREAD

**Issue by Hippogriff** [zouchuhang/3D-PRNN#1]
Can you please provide code for primitive fitting?

**Comment by zouchuhang** [comment]
@Hippogriff Please check "demo.m" in the matlab folder, the current update includes fitting one primitive. You can write your own script to fit one primitive first, remove the fitted 3D points, then fit the next primitive on the remaining shapes.

**Comment by Hippogriff** [comment]
Thank you for the prompt reply.
