### ISSUE TITLE
cannot get data_3dp.zip through wget

### ISSUE THREAD

**Issue by guofeisun** [zouchuhang/3D-PRNN#5]
When I use wget http://czou4.web.engr.illinois.edu/data/data_3dp.zip to download the data, I can only get data_3dp.zip of size 8kb. It seems the zip file is broken.
Are there any other choices to download the data, such as google drive?

**Comment by zouchuhang** [comment]
@guofeisun Just update the link in Readme.md.

**Comment by guofeisun** [comment]
Thanks a lot.
